import React from "react";
import AnimatedBg from "react-animated-bg";

const AnimatedBgImages = () => {
  let getRandom = ({ from, to }) => {
    let min = from;
    let max = to;
    return Math.random() * (+max - +min) + +min;
  };

  let renderAnimatedImages = () => {
    let image_list = [
      'url("/1.png")',
      'url("/2.png")',
      'url("/3.png")',
      'url("/4.png")',
      'url("/5.png")',
      'url("/6.png")',
      'url("/7.png")',
      'url("/8.png")',
      'url("/9.png")'
    ];

    return (
      <div
        style={{
          width: "100%",
          display: "flex",
          flexWrap: "wrap",
          justifyContent: "space-evenly"
        }}
      >
        {[
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0
        ].map((item, index) => {
          return (
            <div style={{ width: "100px" }}>
              <AnimatedBg
                colors={image_list}
                duration={0}
                // duration={0.5}
                // duration={getRandom({ from: 0, to: 3 })}
                // delay={1}
                delay={getRandom({ from: 2, to: 5 })}
                timingFunction="linear"
                // timingFunction="ease-out"
                randomMode
                className={`pz-animated_bg-item`}
              >
                <div style={{ width: "100px", height: "100px" }}></div>
              </AnimatedBg>
            </div>
          );
        })}
      </div>
    );
  };

  return (
    <React.Fragment>
      {renderAnimatedImages()}{" "}
      <style jsx>{`
        .pz-animated_bg-item {
          background-size: contain;
        }
      `}</style>
    </React.Fragment>
  );
};

export default AnimatedBgImages;
